### ISSUE TITLE
Images not being sent to mailchimp

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/mailchimp#9]
Howdy,

I noticed that if you have combinations in your products, then those product images are not being sent to mailchimp at all.

I had the same issue in Prestashop when using the mailchimp default module. Same products (ones that have combinations) are not sent to mailchimp.

**Comment by firstred** [comment]
Wierd. They are sent perfectly fine here. What are the URLs like and what should the URLs be?

**Comment by selwynorren** [comment]
Hey Michael,

Yeah it is wierd, all products work out just fine, its only the ones that have combinations. For instance thsi product of mine
https://www.orren-life.com/everyday-carry/tech/mobile/genuine-leather-executive-folio

It comes out for iPhone 7, iPhone 7 Plus and Samsung s7

None of these images are sent to Mailchimp at all

I also have:
https://www.orren-life.com/everyday-carry/tech/mobile/dualtek-mobile-handset-cover

as well as
https://www.orren-life.com/grooming/beard-care/beard-soap/the-reborn-man-beard-body-soap-bar

**Comment by firstred** [comment]
Are you still having this problem after the latest update?

**Comment by selwynorren** [comment]
Hi, Yeah still the same issue, where products that have combinations are not being pulled through to mailchimp

**Comment by firstred** [comment]
Does 1.2.0 beta 4 solve it?

**Comment by selwynorren** [comment]
Hi Machael,

I uninstalled the old module. Installed the new one I downloaded and when I save the api key I get an error 500. With debug mode on I get the following:
cURL error 6: Could not resolve host: .api.mailchimp.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
at line 186 in file vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php

**Comment by firstred** [comment]
Strange. It should not be making that call.

Thanks for the (useful) feedback.

**Comment by firstred** [comment]
You could try this version if you like:

[mailchimp-v1.2.0-beta.4-GUZZLE_HOTFIX.zip](https://github.com/thirtybees/mailchimp/files/1922650/mailchimp-v1.2.0.zip)

**Comment by selwynorren** [comment]
No Problem. I uninstalled the module, cleared the Database and then re-installed it again and it still gives the same error. Seems like the $dc value is not being picked up and so its trying to connect without that variable?

**Comment by selwynorren** [comment]
Opps seems I was to quick to post. Thanks I will try in now quick

**Comment by selwynorren** [comment]
Thanks Michael, that version fixed the error. Installed successfully. Synced products to mailchimp. The status reflects that 43 items were sent, however in Mailchimp only 10 show

**Comment by firstred** [comment]
Where did you get that number from?

**Comment by firstred** [comment]
If they indeed did not sync, the request and error responses should be on the page "Advanced Parameters > Logs". Anything there?

**Comment by selwynorren** [comment]
So my store has 43 active products (so this is correct). In mailchimp I click on templates / Content Manager / Products. and its only showing me 10 (There are no pagination options).

I found these entries in the logs:
 MailChimp client error: {\"id\":\"6\",\"title\":\"The Reborn Man - Beard & Body Soap Bar\",\"url\":\"https:\\/\\/www.orren-life.com\\/grooming\\/beard-care\\/beard-soap\\/the-reborn-man-beard-body-soap-bar\",\"description\":\"A Humble Restart. A soap bar for your beard, your hair, oh hell, it\'s really good for your entire body. This bar is part of our \\\"The Reborn Man\\\" Collection. This means there are no essential oil fragrances added to the product.\\n100g or 200g of Hand-Crafted Organic Goodness.\",\"vendor\":\"Orren\",\"image_url\":\"https:\\/\\/www.orren-life.com\\/6\\/default.jpg\",\"variants\":[{\"id\":\"6-1\",\"title\":\"The Reborn Man - Beard & Body Soap Bar\",\"sku\":\"RMBB-004-1\",\"price\":40,\"inventory_quantity\":3,\"image_url\":\"https:\\/\\/www.orren-life.com\\/6\\/default.jpg\"},{\"id\":\"6-2\",\"title\":\"The Reborn Man - Beard & Body Soap Bar\",\"sku\":\"RMBB-004-2\",\"price\":80,\"inventory_quantity\":6,\"image_url\":\"https:\\/\\/www.orren-life.com\\/6\\/default.jpg\"},{\"id\":\"6\",\"title\":\"The Reborn Man - Beard & Body Soap Bar\",\"sku\":\"\",\"price\":40,\"inventory_quantity\":1}]} -- {\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Resource Not Found\",\"status\":404,\"detail\":\"The requested resource could not be found.\",\"instance\":\"7e327131-ee85-4672-a60e-50544db7c71f\"} 

What I find interesting here, is the only entries that are in the logs are the ones that appear in mailchimp. There are no entries for all teh products that are not shwing

**Comment by firstred** [comment]
Yeah, that product got accepted in my MailChimp account as well.

It sometimes takes a while for products to show. At least some goods signs here.

**Comment by selwynorren** [comment]
I cleared all the logs and ran the export again. This time around there were no logs to show. Everything seems to be working. However Mailchimp is still only showing 10 products.

I agree there are lots of good signs here. I am mighty impressed with the new module. Looks really amazing. Thanks for your hard work and efforts!

**Comment by firstred** [comment]
You can see the amount of products that got accepted via the API playground: https://api.mailchimp.com/playground/
by entering your key, then navigating to ecommerce => subresources: stores => store number => subresources: products

**Comment by selwynorren** [comment]
Ohh that will help. also you were right. I refreshed the page now and now the pagination shows up and more products are appearing

**Comment by firstred** [comment]
Great news!

**Comment by selwynorren** [comment]
I will monitor it throughout the day and let you know on the success (The playground is thinking really hard) but not showing me the any data, so everything may just be overworked - lol

**Comment by firstred** [comment]
Same here. `us12` and `us13` confirmed overworked, too, lol.

**Comment by selwynorren** [comment]
Ha ha ha. Glad I am not the only one who gets into the overworked status

**Comment by firstred** [comment]
Is the original issue solved now?

**Comment by selwynorren** [comment]
Hi Michael. I am sure it may be. I seems to be having a few other issues. When I try and check the API playground, the eCoomerce does not show anything for me when I select the stores subroutine.

I have even generated an new api key. After yesterdays import it still only showed 12 products and the API playground still does not load

**Comment by firstred** [comment]
It's like your account is stuck. Have you asked MailChimp already what's going on?

**Comment by selwynorren** [comment]
lol was just about to try and find out how to get hold of them

**Comment by firstred** [comment]
Cool, I will do the same because I can still see deleted products and orders, even though I can't acces them via the API anymore. And the playground is stuck here, too.

**Comment by selwynorren** [comment]
Thanks Michael. I truly appreciate your help and support

**Comment by selwynorren** [comment]
Hey Michael,
I have reached out to mailchimp. But all they say to me is they are unfamiliar with Thirty Bees and the mailchimp module is not the one that they are trained for. Pretty much they cant help me. This is after I had explained that it is a fork of PS 1.6

Is there something specific I can send to them?

**Comment by firstred** [comment]
Same here. Back when I was on a paid plan they would let someone from the API team have a look at the calls. From what I recall this was the email address they used: apihelp AT mailchimp DOT com.

**Comment by selwynorren** [comment]
Thanks Michael. I will give them a try.

**Comment by selwynorren** [comment]
The API guys have been in contact, in part thsi is what they have said:
At this time, we are aware of a few various UI issues with our playground which seem to specifically stem from the /ecommerce/ endpoints. As I can replicate the issue (of being unable to load a specific store), this seems related to the issues we are tracking as opposed to some local issue with your browser or computer.

I can forward you the mail if you would like?

**Comment by firstred** [comment]
Sure, michael AT thirtybees DOT com

**Comment by selwynorren** [comment]
perfect thanks I have sent it off to you

**Comment by selwynorren** [comment]
Hey Michael,
Interestingly I downloaded the Advanced REST Client and ran an API call and the data that is returned is indeed only the 12 products that are showing inside mailchimp. So the 43 the modules says its is sending does not seem to be getting there?

**Comment by firstred** [comment]
Can you find anything in the logs?

**Comment by firstred** [comment]
But try another run with the latest version first. Seems you have been running an outdated version for a while.

**Comment by selwynorren** [comment]
Okay I can do that. Every-time in the modules list it showed the module has updates and I have clicked the update button. Has it not been updating?

**Comment by firstred** [comment]
There have just been many updates :P 

Is it done now?

**Comment by selwynorren** [comment]
I am just uninstalling and re-installing the module freshly, I did it before we chatted, however I only ran an update, this time I am doing a complete re-install

**Comment by selwynorren** [comment]
Done, Only 1 product showing at the moment

**Comment by firstred** [comment]
Did you use the `Update all X` buttons as well?

**Comment by selwynorren** [comment]
I do yeah, I have used all three, reset, upload all and upload remaining. They are slowly coming through. We are up to 5 now

**Comment by selwynorren** [comment]
with regard to the logs, there are quite a few errors, here is a sample of 1:

 MailChimp client error: {\"id\":\"45\",\"title\":\"Cork Coasters\",\"url\":\"https:\\/\\/www.orren-life.com\\/my-home\\/home-accents\\/housewares\\/cork-coasters\",\"description\":\"This classic, simple set cork coaster set complements almost any decor. Set includes 4 natural cork coasters providing a soft landing for glasses and cups while protecting your furniture from messy drips.\",\"vendor\":\"Orren\",\"image_url\":\"https:\\/\\/www.orren-life.com\\/198\\/default.jpg\",\"variants\":[{\"id\":\"0\",\"title\":\"Cork Coasters\",\"sku\":\"\",\"price\":55,\"inventory_quantity\":1}]} -- {\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Resource Not Found\",\"status\":404,\"detail\":\"The requested resource could not be found.\",\"instance\":\"a56d0e68-a173-424e-a435-63993e2e7b0f\"} 

Those product are definitely there and are available. It seems however its creating too many escape strings possibly?

When I copy that url its translating it as follows:
https://www.orren-life.com///my-home///home-accents///housewares///cork-coasters

I also get the following error:

 MailChimp client error: {\"id\":\"38\",\"title\":\"Urban Walker Messenger Bag\",\"url\":\"https:\\/\\/www.orren-life.com\\/for-her\\/everyday-carry\\/urban-walker-messenger-bag\",\"description\":\"Travel, for work or play, with this messenger bag that will show off your easy-going, yet classy style. The Urban Walker is made from genuine leather &amp; natural bamboo creating the perfect balance and vintage look.\\u00a0 This bag can hold a 15-inch laptop and still have enough space to keep other valuables.\",\"vendor\":\"Bamboua\",\"image_url\":\"https:\\/\\/www.orren-life.com\\/161\\/default.jpg\",\"variants\":[{\"id\":\"0\",\"title\":\"Urban Walker Messenger Bag\",\"sku\":\"\",\"price\":1899,\"inventory_quantity\":1}]} -- {\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Invalid Resource\",\"status\":400,\"detail\":\"The resource submitted could not be validated. For field-specific details, see the \'errors\' array.\",\"instance\":\"ce8d8ac0-a245-4e38-a4ed-6c15800c644a\",\"errors\":[{\"field\":\"variants.item:0\",\"message\":\"cannot be empty\"}]}

**Comment by firstred** [comment]
Yeah same problem here. The URLs are valid btw.

I have tried to align the way it pushes products with the official module, but that does not work because MailChimp no longer or never accepted variants with ID 0. Seems like MailChimp arrays start at 1.

[![Foo](https://i.redditmedia.com/0zDz4oQmNcG3TyqKHqNMZWtRlzyjqyuM4mJsRgtrQZI.png?s=118a098bfa60a1d149e5179bc5da831f)](https://www.reddit.com/r/ProgrammerHumor/comments/6jea7z/array_indexing_round_2/)

**Comment by firstred** [comment]
Maybe we should prefix the variant IDs with the product ID, because thirty bees has plenty of variants with ID 0 (these are the default combinations).

**Comment by selwynorren** [comment]
Ha ha ha I like that graphic!!! Yeah okay your the boss!! lol

**Comment by firstred** [comment]
I made a new test version, can you see if this one improves things?

[mailchimp-v1.3.1-beta.1.zip](https://github.com/thirtybees/mailchimp/files/1943720/mailchimp-v1.3.1-beta.1.zip)

**Comment by selwynorren** [comment]
Eureka you have done it!! Successfully transferred 43 items.

Just a quick note. I uninstalled, deleted and installed the files. Installed the new version you supplied.

Now after clicking upload all products, it still only uploaded 10, even though the status said 43 files uploaded. However when I checked the logs, nothing was entered there. I then clicked upload remaining products button and it said it was uploading 33 and when I checked logs, nothing entered, however this time all 43 products were listed in teh API. and in mailchimp itself there were 43.

What I had however noticed is that products that only had 1 additional variation, there products were uploaded, however none of teh variatiosn were listed. Example. I have a bracelet in brown and black and only teh default black was sent to mailchimp.

I then activated a product that has quite a few combinations. Then clicked upload remaining products and then I received the first log entry as below

 MailChimp client error: {\"id\":\"44\",\"title\":\"Dualtek Mobile Handset Cover\",\"url\":\"https:\\/\\/www.orren-life.com\\/everyday-carry\\/tech\\/mobile\\/dualtek-mobile-handset-cover\",\"description\":\"Puregear Dualtek Handset Cover\",\"vendor\":\"Puregear\",\"image_url\":\"https:\\/\\/www.orren-life.com\\/185\\/default.jpg\",\"variants\":[{\"id\":\"44-18\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"61394PG\",\"price\":449,\"inventory_quantity\":39,\"image_url\":\"https:\\/\\/www.orren-life.com\\/181\\/default.jpg\"},{\"id\":\"44-18\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"61394PG\",\"price\":449,\"inventory_quantity\":39,\"image_url\":\"https:\\/\\/www.orren-life.com\\/181\\/default.jpg\"},{\"id\":\"44-19\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"61395PG\",\"price\":449,\"inventory_quantity\":244,\"image_url\":\"https:\\/\\/www.orren-life.com\\/192\\/default.jpg\"},{\"id\":\"44-19\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"61395PG\",\"price\":449,\"inventory_quantity\":244,\"image_url\":\"https:\\/\\/www.orren-life.com\\/192\\/default.jpg\"},{\"id\":\"44-20\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"61584PG\",\"price\":449,\"inventory_quantity\":1,\"image_url\":\"https:\\/\\/www.orren-life.com\\/185\\/default.jpg\"},{\"id\":\"44-20\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"61584PG\",\"price\":449,\"inventory_quantity\":1,\"image_url\":\"https:\\/\\/www.orren-life.com\\/185\\/default.jpg\"},{\"id\":\"44-21\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"61585PG\",\"price\":449,\"inventory_quantity\":126,\"image_url\":\"https:\\/\\/www.orren-life.com\\/189\\/default.jpg\"},{\"id\":\"44-21\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"61585PG\",\"price\":449,\"inventory_quantity\":126,\"image_url\":\"https:\\/\\/www.orren-life.com\\/189\\/default.jpg\"},{\"id\":\"44-22\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"61596PG\",\"price\":449,\"inventory_quantity\":101,\"image_url\":\"https:\\/\\/www.orren-life.com\\/185\\/default.jpg\"},{\"id\":\"44-22\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"61596PG\",\"price\":449,\"inventory_quantity\":101,\"image_url\":\"https:\\/\\/www.orren-life.com\\/185\\/default.jpg\"},{\"id\":\"44-23\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"61597PG\",\"price\":449,\"inventory_quantity\":140,\"image_url\":\"https:\\/\\/www.orren-life.com\\/189\\/default.jpg\"},{\"id\":\"44-23\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"61597PG\",\"price\":449,\"inventory_quantity\":140,\"image_url\":\"https:\\/\\/www.orren-life.com\\/189\\/default.jpg\"},{\"id\":\"44-24\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"62044PG\",\"price\":499,\"inventory_quantity\":128,\"image_url\":\"https:\\/\\/www.orren-life.com\\/187\\/default.jpg\"},{\"id\":\"44-24\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"62044PG\",\"price\":499,\"inventory_quantity\":128,\"image_url\":\"https:\\/\\/www.orren-life.com\\/187\\/default.jpg\"},{\"id\":\"44-25\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"62045PG\",\"price\":499,\"inventory_quantity\":71,\"image_url\":\"https:\\/\\/www.orren-life.com\\/192\\/default.jpg\"},{\"id\":\"44-25\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"62045PG\",\"price\":499,\"inventory_quantity\":71,\"image_url\":\"https:\\/\\/www.orren-life.com\\/192\\/default.jpg\"},{\"id\":\"44-26\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"62066PG\",\"price\":499,\"inventory_quantity\":293,\"image_url\":\"https:\\/\\/www.orren-life.com\\/181\\/default.jpg\"},{\"id\":\"44-26\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"62066PG\",\"price\":499,\"inventory_quantity\":293,\"image_url\":\"https:\\/\\/www.orren-life.com\\/181\\/default.jpg\"},{\"id\":\"44-27\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"62067PG\",\"price\":499,\"inventory_quantity\":204,\"image_url\":\"https:\\/\\/www.orren-life.com\\/189\\/default.jpg\"},{\"id\":\"44-27\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"62067PG\",\"price\":499,\"inventory_quantity\":204,\"image_url\":\"https:\\/\\/www.orren-life.com\\/189\\/default.jpg\"},{\"id\":\"44-0\",\"title\":\"Dualtek Mobile Handset Cover\",\"sku\":\"\",\"price\":449,\"inventory_quantity\":0}]} -- {\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Bad Request\",\"status\":400,\"detail\":\"We were unable to process the request. A variant with the provided ID already exists in the account.\",\"instance\":\"e21cda9b-cd40-4a42-b98b-a39dcde13400\"} 

At the end of the day, great Job and thank you!!!

**Comment by firstred** [comment]
You might want to try this one for the last bits:
[mailchimp-v1.3.1-beta.2.zip](https://github.com/thirtybees/mailchimp/files/1944369/mailchimp-v1.3.1-beta.2.zip)

**Comment by selwynorren** [comment]
Hey Michael,

Okay I installed the new version. but I still have the same issue. If I select upload all products, then 10 first upload, then when select upload remaining products, then the balance 33 are uploaded.

I also cleared everything, broke the connection with Mailchimp and then re-uploaded it all. This time instead of uploading all product first I used uploading remaining product first, then uploaded everything immediately.

The variation issue still remains. I am only getting this error on this specific product, which I normally deactivate, however none of the products variation are being sent to Mailchimp.

However I think the latter should be a different Github issue?

**Comment by firstred** [comment]
Looks like we need extra logic to remove the variants before updating/adding a product. What a pain!

**Comment by Dh42** [comment]
![Soon](http://i0.kym-cdn.com/entries/icons/mobile/000/005/673/sooon.jpg)

**Comment by firstred** [comment]
Found something already, beta 3: 
[mailchimp-v1.3.1-beta.3.zip](https://github.com/thirtybees/mailchimp/files/1944686/mailchimp-v1.3.1-beta.3.zip)

**Comment by selwynorren** [comment]
Well I take my hat off to you guys who can code this stuff. I know procedural PHP, yet somehow in OOPHP I feel like a lost fart in a whirlwind. Thanks Michael, Ill install it now and give it a test run

**Comment by selwynorren** [comment]
Okay it works. Great Job!! I activated the product with so many variations and it sent it to maichimp without any issues.

The initial click on send all products to mailchimp still only sends 10 products. Then clicking send remainder products does the trick. Also click send remainder products right out the gate send everything as well.

At some point d you think it would be possible to send the variation images to Mailchimp as well as a future release? Here I am thinking it send the image set as default for the product, but for each variation we also set a default image. It would be great to send that as well. I can make a separate issue for that as I believe this issue can officially be marked as resolved.

Thank you so much

**Comment by firstred** [comment]
Looks like the variant image array wasn't accessible while syncing. I just pushed a few commits to handle variant images. It now also fills the [images array](https://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/stores/products/variants/) with the variant IDs that are tied to the images.

**Comment by selwynorren** [comment]
oh wow fantastic. Ill download the new version and install it and test for you. Will let you know shortly

**Comment by selwynorren** [comment]
Michael, I gave it a test, however the combination images don't go through to mailchimp. So the primary Image for the Product does and that works really well. However the additional combination images do not go through.

for example, this product listed here:
https://www.orren-life.com/everyday-carry/wallets/minimalist-wallets/minimalist-wallet

Has a green and orange. Default Image is Green and that goes through very well to Mailchimp. However it also has an orange variant and this does not get pushed.

Should I open a separate issue for this? as teh core issue has been resolved

**Comment by firstred** [comment]
What did you download? Did you try the latest source or older code?

**Comment by selwynorren** [comment]
Hey Michael. I downloaded teh latest source, which brought it up to ver 1.4

**Comment by firstred** [comment]
Great feedback. Seems like the Product::getCombinationImages method does not automatically return all images for combinations that have no specific images. Default behavior is to show all images, but the method does not return all by default. So one solution is to assign all product images to that specific attribute ID.

**Comment by selwynorren** [comment]
Thanks Michael. Will Mailchimp accept duplicate ID's for the images?

**Comment by firstred** [comment]
Yes, the `images` array will inform MailChimp about which variant IDs belong to which images. It's a bit redundant, but this is the format MailChimp supports.

**Comment by selwynorren** [comment]
And this is why they (Hopefully) pay you the big money.

I am ready to test whenever you let me know

**Comment by firstred** [comment]
You can try the latest source if you like.

**Comment by selwynorren** [comment]
Michael, so I uploaded the new version over the old one, disconnected the site in Mailchimp, uninstalled and reinstalled the module in TB. Connected everything, but this time when I try and upload the images to Mailchimp it says 0 images uploaded. This happens if I select upload all product or even upload remaining products. I have also reset the product sync data.

I also looked in the logs and nothing is recorded there at all. I also have debug activated and nothing shows any errors there either

**Comment by firstred** [comment]
Then you're likely checking too soon. Only by checking the API you can immediately see the results.

**Comment by selwynorren** [comment]
Yeah I thought that as well, however I am checking the API directly and it shows 0

**Comment by firstred** [comment]
Oh damn, it still has my tests in the code, like `$sql->where('ps.`id_product` = 61');` 
Yeah, that's not going to help. :stuck_out_tongue: 
Let me give it a few more tries first and clean up the code...

**Comment by selwynorren** [comment]
Ha ha ha, Ill hang on

**Comment by firstred** [comment]
Yes, got it now. Make sure you're on the latest source.

**Comment by selwynorren** [comment]
Right so we have major progress Michael. Whats happening now is its not sending everything to mailchimp. At last check with the api, I am only counting 8 products. However every image is now being sent. Even if its not a combination product. On Mailchimp side its grouping them as versions. So it shows the primary image but in teh lower right hand corner it shows a 3 or 4 or whatever number of images were loaded with that product.

Then when there is a combination product, it shows that combination image as well. (So in my case I only have one product that made it through that is a combination product and that image is duplicated.

So this means the core of the script is working, however instead of just transferring the main image per combination, its now sending every image per product. then its also grouping every image under the unique id so it shows it as 1 image with multiple variations.

I hope I am making sense?

Oh also in the logs I see a few of these entries:
 MailChimp client error: {\"id\":\"2\",\"title\":\"The Hunts Man - Beard oil\",\"url\":\"https:\\/\\/www.orren-life.com\\/grooming\\/beard-care\\/beard-oil\\/the-hunts-man-beard-oil\",\"description\":\"The Hunts Man Beard Oil.\\n30ml of Hand-Crafted Goodness.\\nBack to Nature. Apply rand coin size amount to beard. Test for allergens before use.\",\"vendor\":\"Orren\",\"image_url\":\"https:\\/\\/www.orren-life.com\\/2\\/default.jpg\",\"variants\":[{\"id\":\"2-0\",\"title\":\"The Hunts Man - Beard oil\",\"sku\":\"\",\"price\":180,\"inventory_quantity\":5,\"image_url\":\"https:\\/\\/www.orren-life.com\\/2\\/default.jpg\"}],\"images\":[{\"id\":\"1\",\"url\":\"https:\\/\\/www.orren-life.com\\/1\\/default.jpg\",\"variant_ids\":[\"1-0\"]},{\"id\":\"2\",\"url\":\"https:\\/\\/www.orren-life.com\\/2\\/default.jpg\",\"variant_ids\":[\"2-0\"]}]} -- {\"type\":\"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\",\"title\":\"Bad Request\",\"status\":400,\"detail\":\"We were unable to process the request. An image with id 1 already exists in the account.\",\"instance\":\"cc079b0a-8c7c-413b-8d7a-8d83d8716293\"}

**Comment by firstred** [comment]
Seems like this is what it should do:
- Send all images if a combination does not have specific images selected (because tb shows all by 
default)
- Stop sending the default combination when there are attributes

The counter was broken a few commits ago so it could not make it past 10 products. Should be better now with the latest source. I think the above guidelines is how we should be pushing products to MailChimp.

**Comment by selwynorren** [comment]
Michael, yeah that sounds like a great plan. Ill test and get back to you

**Comment by firstred** [comment]
Just added a commit. The preliminary DELETEs should no longer be used. That prevented the images array from filling, which should be better with the latest commit added.

**Comment by selwynorren** [comment]
Works like a charm Michael. See attached screenshot.
so many of the products on that screenshot are only single combination products, however all their images are still being sent. The wallet you see there listed in Black/Green however is a combination product.

Would it not be better to only send the default image per product. in TB each combination must have an image attached to that specific combination. My concern is, in Mailchimp, how would you use the image combinations in the mailers that go out? So how would it show that the Green wallet was ordered for example, or if we are sending a marketing email, how could we show the other images that are "Hidden".
![screenshot-2018-4-30 templates mailchimp](https://user-images.githubusercontent.com/570607/39418867-1b1d40e4-4c5d-11e8-853f-7197c784a2eb.png)

**Comment by firstred** [comment]
Many users assign all images to the combinations by leaving the checkboxes unticked. The `image_url` option has the default image in it. I have no idea how MailChimp handles it, but merchants leaving the image selection blank by default expect all images to be assigned to a product, which is the default behavior. If you don't like that, only tick the images that belong to a combination.

**Comment by selwynorren** [comment]
Hey Michael, thanks for your feedback. I think lets mark this issue off as solved. Everything works really well and compared to when we started off, this is a major milestone.

Just regarding your last comment. I only have the appropriate images ticked per combination. I don't have non related images ticked of any given combination. All images per product are being sent. So in the case of the 2 way radios or any of the products in the image above. There are no combinations, there are as many images. In the case of the black and lime green wallet this is the only product in this image that has combinations. Only the relevant images are ticked per combination.

Bottom line is all images are sent and that's the most important part for me.

Again, thanks so much for every ounce of work you have put into this. You and the team are crazy awesome.

**Comment by firstred** [comment]
Thanks!

If you could share the result of a `GET https://<dc>.api.mailchimp.com/3.0ecommerce/stores/tbstore_<id_shop>`/products/<id_product>` of one of the products with too many images, then that would be really nice, so we can examine if there are too many images. I haven't seen it assign too many here, but like you I think I still see too many images. Maybe MailChimp does that on purpose... Who knows?

**Comment by selwynorren** [comment]
hey Michael,

I am using Advanced REST client for Linux and this is the result. Is this what you are looking for? This is for the specific product in question

{"id":"29","title":"Minimalist Wallet","handle":"","url":"https://www.orren-life.com/everyday-carry/wallets/minimalist-wallets/minimalist-wallet","description":"<p>Our Minimalist Wallet is unlike other wallets you have seen, this stylish wallet isn't too bulky. Suitable for formal or leisure attire - with business suits, jeans or casual trousers.</p>","type":"","vendor":"Orren","image_url":"https://www.orren-life.com/109/default.jpg","variants":[{"id":"29-3","title":"Minimalist Wallet","url":"","sku":"SMW-001G","price":110,"inventory_quantity":6,"image_url":"https://www.orren-life.com/109/default.jpg","backorders":"","visibility":"","created_at":"2018-04-30T07:51:33+00:00","updated_at":"2018-04-30T07:51:33+00:00","_links":[{"rel":"self","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29/variants/29-3","method":"GET","targetSchema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Variants/Response.json"},{"rel":"parent","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29","method":"GET","targetSchema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Variants/CollectionResponse.json"},{"rel":"update","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29/variants/29-3","method":"PATCH","targetSchema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Variants/Response.json","schema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Variants/PATCH.json"},{"rel":"upsert","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29/variants/29-3","method":"PUT","targetSchema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Variants/Response.json","schema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Variants/PUT.json"},{"rel":"delete","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29/variants/29-3","method":"DELETE"}]},{"id":"29-4","title":"Minimalist Wallet","url":"","sku":"SMW-001O","price":110,"inventory_quantity":6,"image_url":"https://www.orren-life.com/114/default.jpg","backorders":"","visibility":"","created_at":"2018-04-30T07:51:33+00:00","updated_at":"2018-04-30T07:51:33+00:00","_links":[{"rel":"self","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29/variants/29-4","method":"GET","targetSchema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Variants/Response.json"},{"rel":"parent","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29","method":"GET","targetSchema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Variants/CollectionResponse.json"},{"rel":"update","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29/variants/29-4","method":"PATCH","targetSchema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Variants/Response.json","schema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Variants/PATCH.json"},{"rel":"upsert","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29/variants/29-4","method":"PUT","targetSchema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Variants/Response.json","schema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Variants/PUT.json"},{"rel":"delete","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29/variants/29-4","method":"DELETE"}]}],"images":[{"id":"109","url":"https://www.orren-life.com/109/default.jpg","variant_ids":["29-3"]},{"id":"110","url":"https://www.orren-life.com/110/default.jpg","variant_ids":["29-3"]},{"id":"111","url":"https://www.orren-life.com/111/default.jpg","variant_ids":["29-3"]},{"id":"112","url":"https://www.orren-life.com/112/default.jpg","variant_ids":["29-3"]},{"id":"113","url":"https://www.orren-life.com/113/default.jpg","variant_ids":["29-3"]},{"id":"114","url":"https://www.orren-life.com/114/default.jpg","variant_ids":["29-4"]},{"id":"115","url":"https://www.orren-life.com/115/default.jpg","variant_ids":["29-4"]},{"id":"116","url":"https://www.orren-life.com/116/default.jpg","variant_ids":["29-4"]},{"id":"117","url":"https://www.orren-life.com/117/default.jpg","variant_ids":["29-4"]},{"id":"118","url":"https://www.orren-life.com/118/default.jpg","variant_ids":["29-4"]}],"published_at_foreign":"","_links":[{"rel":"self","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29","method":"GET","targetSchema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Response.json"},{"rel":"parent","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products","method":"GET","targetSchema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/CollectionResponse.json"},{"rel":"update","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29","method":"PATCH","targetSchema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Response.json","schema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/PATCH.json"},{"rel":"delete","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29","method":"DELETE"},{"rel":"variants","href":"https://us13.api.mailchimp.com/3.0/ecommerce/stores/tbstore_1/products/29/variants","method":"GET","targetSchema":"https://us13.api.mailchimp.com/schema/3.0/Definitions/Ecommerce/Stores/Products/Variants/CollectionResponse.json"}]}

I am also more than happy to grant you access to the back-office of my store if it will help any

**Comment by firstred** [comment]
Sure, let's get to the bottom of this. Btw is your browser getting a bit slow in this topic, too? :P

**Comment by selwynorren** [comment]
Ha ha ha yeah it is indeed.

**Comment by firstred** [comment]
According to the response 5 images are assigned to attribute ID 3 and 5 to attribute ID 4.

**Comment by selwynorren** [comment]
That's correct yes, but they are 5 different images each combination:

But here is something interesting which I never noticed before. and I think this lies at the root of the issue. In the back-end I have two combination, green and orange and I only have the relevant images ticked per colour combination. I have the default combination set for the green colour.

When the product load on the visitor side, it shows all images. When I select the orange colour swatch, instead of filtering the images to show only that combination, it scrolls to that combinations colours, when I select the green swatch it does nothing. Could it be, that its not separating the colours based on combinations properly, hence why the send to Mailchimp does not go 100% as planned?

Here is a link to my old site where the product was loaded. I have disabled ordering as I dont want anyone making purchases on thsi site
https://orren.co.za/everyday-carry/47-slim-magic-wallet.html

This was my PS site. You will see that when you load on the product it shows all images. When you select the relevant swatch it only shows the specific images for that combination.

This is the link to my TB site for the same product and same combination and image set
https://www.orren-life.com/everyday-carry/wallets/minimalist-wallets/minimalist-wallet

I am also adding the screen capture of the combination setup for the images in my TB site where you can see the relevant images are selected.
![screenshot-2018-4-30 products edit minimalist wallet - green](https://user-images.githubusercontent.com/570607/39438085-2a640d8a-4ca3-11e8-956a-7a2b5807efe6.png)
![screenshot-2018-4-30 products edit minimalist wallet - orange](https://user-images.githubusercontent.com/570607/39438092-33119588-4ca3-11e8-8c20-6694cf62b855.png)

**Comment by firstred** [comment]
Closing this one due to inactivity and my browser crashes when I try to open it :stuck_out_tongue:
